#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
using namespace std;

#if 0
double Division(int a, int b)
{
	//当b==0时抛出异常
	if (b == 0)
		throw "Divison by zero condition!";
	else
		return ((double)a / (double)b);
}

void Func()
{
	int len, time;
	cin >> len >> time;
	cout << Division(len, time) << endl;
}

int main()
{
	try
	{
		Func();
	}
	catch (const char*errmsg)
	{
		cout << errmsg << endl;
	}
	catch (...)
	{
		cout << "unkown exception" << endl;
	}

	system("pause");
	return 0;
}
#endif

//异常的重新抛出
double Division(int a, int b)
{
	//当b==0时抛出异常
	if (b == 0)
	{
		throw "Division by zero condition!";
	}
	return (double)a / (double)b;
}

void Func()
{
	//这里可以看到如果发生除0错误抛出异常，另外下面的array没有得到释放。
	//所以这里捕获异常后并不处理异常，异常还是交给外面处理
	//这里捕获了再重新抛出去
	int* array = new int[10];
	try
	{
		int len, time;
		cin >> len >> time;
		cout << Division(len, time) << endl;
	}

	catch (...)
	{
		cout << "delete[]" << array << endl;
		delete[]array;
		throw;
	}

	cout << "delete[]" << array << endl;

	delete[]array;
}

int main()
{
	try
	{
		Func();
	}
	catch (const char* errmsg)
	{
		cout << errmsg << endl;
	}

	system("pause");
	return 0;
}
